// Copyright (C) 2024-2025 Zormeister, All rights reserved. Licensed under the BSD-3 Clause License.

#pragma once

/* Technically a piece of the Aux component, divide them anyways */
#define UART1_BASE AUX_BASE + 0x40

#define rUART1_IO 0x0
#define UART1_IO__MASK 0xFF

#define rUART1_IRQ_ENABLE 0x4
#define UART1_IRQ_ENABLE__ENABLE_TX_IRQ_MASK (1 << 0)
#define UART1_IRQ_ENABLE__ENABLE_TX_IRQ_SHIFT 0
#define UART1_IRQ_ENABLE__ENABLE_RX_IRQ_MASK (1 << 1)
#define UART1_IRQ_ENABLE__ENABLE_RX_IRQ_SHIFT 1
#define UART1_IRQ_ENABLE__16BR_MASK 0xFF

#define rUART1_IRQ_IDENTIFY 0x8
#define UART1_IRQ_IDENTIFY__IRQ_PENDING_MASK (1 << 0)
#define UART1_IRQ_IDENTIFY__IRQ_PENDING_SHIFT 0
#define UART1_IRQ_IDENTIFY__IRQ_ID_FIFO_CLEAR_BITS_MASK (1 << 1 | 1 << 2)

#define rUART1_LINE_CNTL 0xC
#define UART1_LINE_CNTL__DATA_SIZE_MASK (1 << 0)
#define UART1_LINE_CNTL__DATA_SIZE_SHIFT 0
#define UART1_LINE_CNTL__BREAK_MASK (1 << 6)
#define UART1_LINE_CNTL__BREAK_SHIFT 6
#define UART1_LINE_CNTL__DLAB_ACCESS_MASK (1 << 7)
#define UART1_LINE_CNTL__DLAB_ACCESS_SHIFT 7

#define rUART1_MODEM_CNTL 0x10
#define UART1_MODEM_CNTL__RTS_MASK (1 << 0)
#define UART1_MODEL_CNTL__RTS_SHIFT 0

#define rUART1_LINE_STATUS 0x14
#define UART1_LINE_STATUS__DATA_READY_MASK (1 << 0)
#define UART1_LINE_STATUS__DATA_READY_SHIFT 0
#define UART1_LINE_STATUS__RX_OVERRUN_MASK (1 << 1)
#define UART1_LINE_STATUS__RX_OVERRUN_SHIFT 1
#define UART1_LINE_STATUS__TX_EMPTY_MASK (1 << 5)
#define UART1_LINE_STATUS__TX_EMPTY_SHIFT 5
#define UART1_LINE_STATUS__TX_IDLE_MASK (1 << 6)
#define UART1_LINE_STATUS__TX_IDLE_SHIFT 6

#define rUART1_MODEM_STATUS 0x18
#define UART1_MODEM_STATUS__CTS_STATUS_MASK (1 << 4)
#define UART1_MODEM_STATUS__CTS_STATUS_SHIFT 4

#define rUART1_SCRATCH 0x1C
#define UART1_SCRATCH__SCRATCH_MASK 0xFF

#define rUART1_CNTL 0x20
#define UART1_CNTL__RX_ENABLE_MASK (1 << 0)
#define UART1_CNTL__RX_ENABLE_SHIFT 0

#define rUART1_STATUS 0x24

#define rUART1_BAUDRATE 0x28
